In [336]:
import pandas as pd
import numpy as np

df = pd.read_excel(r'G:\WFH\20211226_01\ECS_spec.xlsx', sheet_name='Sheet1')
df1 = pd.read_excel(r'G:\WFH\20211226_01\BGB-16673-102_V1.0.xlsx', sheet_name='CheckActions')

In [337]:
pd.set_option('display.max_rows', 3)
pd.set_option('display.max_columns', 10)

In [338]:
df = pd.DataFrame(df,columns=['Version#','Serial #','Edit Check Name','Folder OID','Form Name','Form OID','Field Label',
                               'Field OID','Related Field OID','Query Text/Mapping Text/Email','Check Type','Assigner'])
df

,Version#,Serial #,Edit Check Name,Folder OID,Form Name,...,Field OID,Related Field OID,Query Text/Mapping Text/Email,Check Type,Assigner
0,0.1,1,DYN_CTMSTAG_CF_DS_EOS\nDYN_CTMSTAG_CF_DS_IC\nD...,Subject,Patient,...,NaN,NaN,NaN,Status,wei sun
...,...,...,...,...,...,...,...,...,...,...,...
1101,0.1,1109,SYS_REQ_RSALRES|RS_PET,"SCR, RASS\nRASFUP\nRALFUP\nRASUNS",Deauville Five-Point Scale,...,RSALRES,NaN,Data is required. Please complete.,Field Checks,Yichi

In [339]:
df = df.rename(columns={"Edit Check Name": "CheckName"})
df

,Version#,Serial #,CheckName,Folder OID,Form Name,...,Field OID,Related Field OID,Query Text/Mapping Text/Email,Check Type,Assigner
0,0.1,1,DYN_CTMSTAG_CF_DS_EOS\nDYN_CTMSTAG_CF_DS_IC\nD...,Subject,Patient,...,NaN,NaN,NaN,Status,wei sun
...,...,...,...,...,...,...,...,...,...,...,...
1101,0.1,1109,SYS_REQ_RSALRES|RS_PET,"SCR, RASS\nRASFUP\nRALFUP\nRASUNS",Deauville Five-Point Scale,...,RSALRES,NaN,Data is required. Please complete.,Field Checks,Yichi

In [340]:
#df['CheckName'].str.strip()
#df

In [341]:
df1 = pd.DataFrame(df1,columns=['CheckName','ActionType','ActionString'])
#df1

In [342]:
df1 = df1[~df1['ActionString'].isna()]

In [343]:
join = pd.merge(df, df1, how='left', on=['CheckName'])
join

,Version#,Serial #,CheckName,Folder OID,Form Name,...,Query Text/Mapping Text/Email,Check Type,Assigner,ActionType,ActionString
0,0.1,1,DYN_CTMSTAG_CF_DS_EOS\nDYN_CTMSTAG_CF_DS_IC\nD...,Subject,Patient,...,NaN,Status,wei sun,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1101,0.1,1109,SYS_REQ_RSALRES|RS_PET,"SCR, RASS\nRASFUP\nRALFUP\nRASUNS",Deauville Five-Point Scale,...,Data is required. Please complete.,Field Checks,Yichi,NaN,NaN

In [344]:
join['IsEqual'] = (join['Query Text/Mapping Text/Email']==join['ActionString'])
join

,Version#,Serial #,CheckName,Folder OID,Form Name,...,Check Type,Assigner,ActionType,ActionString,IsEqual
0,0.1,1,DYN_CTMSTAG_CF_DS_EOS\nDYN_CTMSTAG_CF_DS_IC\nD...,Subject,Patient,...,Status,wei sun,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...
1101,0.1,1109,SYS_REQ_RSALRES|RS_PET,"SCR, RASS\nRASFUP\nRALFUP\nRASUNS",Deauville Five-Point Scale,...,Field Checks,Yichi,NaN,NaN,False

In [345]:
join.to_excel(r'G:\WFH\20211226_01\EC_InternalQC_CheckQueryText.xlsx')