In [877]:
import pandas as pd
import numpy as np

df = pd.read_excel(r'G:\python\EC_QC\als.xlsx', sheet_name = 'CheckSteps')
df.head()

,CheckName,StepOrdinal,CheckFunction,StaticValue,DataFormat,VariableOID,FolderOID,FormOID,FieldOID,RecordPosition,CustomFunction,LogicalRecordPosition,Scope,OrderBy,FormRepeatNumber,FolderRepeatNumber
0,DYN_SV_SET_SVDELYN_VISIBLE,1,NaN,NaN,CodedValue,SVSTAT,NaN,SV,SVSTAT,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,DYN_SV_SET_SVDELYN_VISIBLE,2,NaN,Done,$5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,DYN_SV_SET_SVDELYN_VISIBLE,3,IsEqualTo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,DYN_SV_SET_SVDRES_VISIBLE,1,NaN,NaN,CodedValue,SVSTAT,NaN,SV,SVSTAT,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,DYN_SV_SET_SVDRES_VISIBLE,2,NaN,Done,$10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [878]:
pd.set_option('display.max_rows', 5)
pd.set_option('display.max_columns', 31)

In [879]:
codedValue = df[df['DataFormat'].isin(['CodedValue', 'StandardValue'])]
codedValue.head()

,CheckName,StepOrdinal,CheckFunction,StaticValue,DataFormat,VariableOID,FolderOID,FormOID,FieldOID,RecordPosition,CustomFunction,LogicalRecordPosition,Scope,OrderBy,FormRepeatNumber,FolderRepeatNumber
0,DYN_SV_SET_SVDELYN_VISIBLE,1,NaN,NaN,CodedValue,SVSTAT,NaN,SV,SVSTAT,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3,DYN_SV_SET_SVDRES_VISIBLE,1,NaN,NaN,CodedValue,SVSTAT,NaN,SV,SVSTAT,0.0,NaN,NaN,NaN,NaN,NaN,NaN
6,DYN_SV_SET_SVDRES_VISIBLE,4,NaN,NaN,CodedValue,SVDELYN,NaN,SV,SVDELYN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
10,DYN_SV_SET_SVMRES_VISIBLE,1,NaN,NaN,CodedValue,SVSTAT,NaN,SV,SVSTAT,0.0,NaN,NaN,NaN,NaN,NaN,NaN
13,DYN_SV_SET_SVSTDAT_VISIBLE,1,NaN,NaN,CodedValue,SVSTAT,NaN,SV,SVSTAT,0.0,NaN,NaN,NaN,NaN,NaN,NaN

In [880]:
codedValue['StepOrdinal'] = codedValue['StepOrdinal'] + 1
codedValue.head()

<ipython-input-880-6db77fd8e9ab>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  codedValue['StepOrdinal'] = codedValue['StepOrdinal'] + 1

,CheckName,StepOrdinal,CheckFunction,StaticValue,DataFormat,VariableOID,FolderOID,FormOID,FieldOID,RecordPosition,CustomFunction,LogicalRecordPosition,Scope,OrderBy,FormRepeatNumber,FolderRepeatNumber
0,DYN_SV_SET_SVDELYN_VISIBLE,2,NaN,NaN,CodedValue,SVSTAT,NaN,SV,SVSTAT,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3,DYN_SV_SET_SVDRES_VISIBLE,2,NaN,NaN,CodedValue,SVSTAT,NaN,SV,SVSTAT,0.0,NaN,NaN,NaN,NaN,NaN,NaN
6,DYN_SV_SET_SVDRES_VISIBLE,5,NaN,NaN,CodedValue,SVDELYN,NaN,SV,SVDELYN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
10,DYN_SV_SET_SVMRES_VISIBLE,2,NaN,NaN,CodedValue,SVSTAT,NaN,SV,SVSTAT,0.0,NaN,NaN,NaN,NaN,NaN,NaN
13,DYN_SV_SET_SVSTDAT_VISIBLE,2,NaN,NaN,CodedValue,SVSTAT,NaN,SV,SVSTAT,0.0,NaN,NaN,NaN,NaN,NaN,NaN

In [881]:
StaticValue = df[~df['StaticValue'].isna()]
StaticValue.head()

,CheckName,StepOrdinal,CheckFunction,StaticValue,DataFormat,VariableOID,FolderOID,FormOID,FieldOID,RecordPosition,CustomFunction,LogicalRecordPosition,Scope,OrderBy,FormRepeatNumber,FolderRepeatNumber
1,DYN_SV_SET_SVDELYN_VISIBLE,2,NaN,Done,$5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,DYN_SV_SET_SVDRES_VISIBLE,2,NaN,Done,$10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,DYN_SV_SET_SVDRES_VISIBLE,5,NaN,Yes,$10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,DYN_SV_SET_SVMRES_VISIBLE,2,NaN,Not done,$10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,DYN_SV_SET_SVSTDAT_VISIBLE,2,NaN,Done,$10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [882]:
merge = pd.merge(codedValue,StaticValue,how='left',on=['CheckName','StepOrdinal'])
merge

,CheckName,StepOrdinal,CheckFunction_x,StaticValue_x,DataFormat_x,VariableOID_x,FolderOID_x,FormOID_x,FieldOID_x,RecordPosition_x,CustomFunction_x,LogicalRecordPosition_x,Scope_x,OrderBy_x,FormRepeatNumber_x,FolderRepeatNumber_x,CheckFunction_y,StaticValue_y,DataFormat_y,VariableOID_y,FolderOID_y,FormOID_y,FieldOID_y,RecordPosition_y,CustomFunction_y,LogicalRecordPosition_y,Scope_y,OrderBy_y,FormRepeatNumber_y,FolderRepeatNumber_y
0,DYN_SV_SET_SVDELYN_VISIBLE,2,NaN,NaN,CodedValue,SVSTAT,NaN,SV,SVSTAT,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Done,$5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,DYN_SV_SET_SVDRES_VISIBLE,2,NaN,NaN,CodedValue,SVSTAT,NaN,SV,SVSTAT,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Done,$10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3689,Chk_SCR_DS_IC_ICOBM_MHTERM8,5,NaN,NaN,CodedValue,MHTERM8,SCR,MH_DHH,MHTERM8,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WM,$2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3690,Chk_SCR_DS_IC_ICOBM_MHTERM8,8,NaN,NaN,CodedValue,MHTERM8,SCR,MH_DHH,MHTERM8,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [883]:
merge.to_excel(r'G:\python\EC_QC\merge_beforeRemDupli.xlsx',index=False)

In [884]:
merge = pd.DataFrame(merge,columns=['CheckName','StepOrdinal_x','DataFormat_x','VariableOID_x','FolderOID_x','FormOID_x','FieldOID_x','RecordPosition_x','StepOrdinal_y','StaticValue_y','DataFormat_y'])
merge

,CheckName,StepOrdinal_x,DataFormat_x,VariableOID_x,FolderOID_x,FormOID_x,FieldOID_x,RecordPosition_x,StepOrdinal_y,StaticValue_y,DataFormat_y
0,DYN_SV_SET_SVDELYN_VISIBLE,NaN,CodedValue,SVSTAT,NaN,SV,SVSTAT,0.0,NaN,Done,$5
1,DYN_SV_SET_SVDRES_VISIBLE,NaN,CodedValue,SVSTAT,NaN,SV,SVSTAT,0.0,NaN,Done,$10
...,...,...,...,...,...,...,...,...,...,...,...
3689,Chk_SCR_DS_IC_ICOBM_MHTERM8,NaN,CodedValue,MHTERM8,SCR,MH_DHH,MHTERM8,0.0,NaN,WM,$2
3690,Chk_SCR_DS_IC_ICOBM_MHTERM8,NaN,CodedValue,MHTERM8,SCR,MH_DHH,MHTERM8,0.0,NaN,NaN,NaN

In [885]:
#merge = merge.drop_duplicates(subset=['CheckName','DataFormat_x','VariableOID_x'])
#merge

In [886]:
merge = pd.DataFrame(merge,columns=['CheckName','DataFormat_x','VariableOID_x','FolderOID_x','FormOID_x','FieldOID_x','RecordPosition_x','StaticValue_y','DataFormat_y'])
merge

,CheckName,DataFormat_x,VariableOID_x,FolderOID_x,FormOID_x,FieldOID_x,RecordPosition_x,StaticValue_y,DataFormat_y
0,DYN_SV_SET_SVDELYN_VISIBLE,CodedValue,SVSTAT,NaN,SV,SVSTAT,0.0,Done,$5
1,DYN_SV_SET_SVDRES_VISIBLE,CodedValue,SVSTAT,NaN,SV,SVSTAT,0.0,Done,$10
...,...,...,...,...,...,...,...,...,...
3689,Chk_SCR_DS_IC_ICOBM_MHTERM8,CodedValue,MHTERM8,SCR,MH_DHH,MHTERM8,0.0,WM,$2
3690,Chk_SCR_DS_IC_ICOBM_MHTERM8,CodedValue,MHTERM8,SCR,MH_DHH,MHTERM8,0.0,NaN,NaN

In [887]:
merge.to_excel(r'G:\python\EC_QC\merge.xlsx',index=False)

In [888]:
# merge = CheckSteps

In [889]:
df1 = pd.read_excel(r'G:\python\EC_QC\als.xlsx', sheet_name = 'Fields')
df1.head()

,FormOID,FieldOID,Ordinal,DraftFieldNumber,DraftFieldName,DraftFieldActive,VariableOID,DataFormat,DataDictionaryName,UnitDictionaryName,CodingDictionary,ControlType,AcceptableFileExtensions,IndentLevel,PreText,...,DoesNotBreakSignature,LowerRange,UpperRange,NCLowerRange,NCUpperRange,ViewRestrictions,EntryRestrictions,ReviewGroups,IsVisualVerify,FDownloadedFromObjectId,FSourceObjectId,VDownloadedFromObjectId,VSourceObjectId,FSourceUrlId,VSourceUrlId
0,SUBJECT,SUBJID,1,NaN,SUBJID,True,SUBJID,$15,NaN,NaN,NaN,Text,NaN,0,Patient number,...,False,NaN,NaN,NaN,NaN,NaN,NaN,Data Management,False,8675968,8582370,7811530.0,7719863.0,NaN,NaN
1,SUBJECT,COUNTRY,6,NaN,COUNTRY,True,COUNTRY,$20,NaN,NaN,NaN,LongText,NaN,0,Country,...,True,NaN,NaN,NaN,NaN,NaN,"Coder Import Role,Clinical Research Associate,...",NaN,False,8675969,8582369,7811531.0,7719864.0,NaN,NaN
2,SUBJECT,CCGLINK,14,NaN,CCGLINK,True,CCGLINK,1,NaN,NaN,NaN,Text,NaN,0,"<a href="" https://beigeneclinical.mdsol.com/Me...",...,True,NaN,NaN,NaN,NaN,"eCRF PDF,Data PDF","Coder Import Role,OL Role,Clinical Research As...",NaN,False,8675970,8582368,7811532.0,7719865.0,NaN,NaN
3,SV,SVSTAT,1,NaN,SVSTAT,True,SVSTAT,$10,SVSTAT,NaN,NaN,DropDownList,NaN,0,Visit status,...,False,NaN,NaN,NaN,NaN,NaN,NaN,Data Management,False,8675971,8582375,7811533.0,7719866.0,NaN,NaN
4,SV,SVSTDAT,2,NaN,SVSTDAT,True,SVSTDAT,dd MMM yyyy,NaN,NaN,NaN,DateTime,NaN,0,Date of visit,...,False,NaN,NaN,NaN,NaN,NaN,NaN,Data Management,False,8675972,8582376,7811534.0,7719867.0,NaN,NaN

In [890]:
df1 = df1[~df1['DataDictionaryName'].isna()]
df1

,FormOID,FieldOID,Ordinal,DraftFieldNumber,DraftFieldName,DraftFieldActive,VariableOID,DataFormat,DataDictionaryName,UnitDictionaryName,CodingDictionary,ControlType,AcceptableFileExtensions,IndentLevel,PreText,...,DoesNotBreakSignature,LowerRange,UpperRange,NCLowerRange,NCUpperRange,ViewRestrictions,EntryRestrictions,ReviewGroups,IsVisualVerify,FDownloadedFromObjectId,FSourceObjectId,VDownloadedFromObjectId,VSourceObjectId,FSourceUrlId,VSourceUrlId
3,SV,SVSTAT,1,NaN,SVSTAT,True,SVSTAT,$10,SVSTAT,NaN,NaN,DropDownList,NaN,0,Visit status,...,False,NaN,NaN,NaN,NaN,NaN,NaN,Data Management,False,8675971,8582375,7811533.0,7719866.0,NaN,NaN
6,SV,SVMRES,10,NaN,SVMRES,True,SVMRES,$10,COVIDND,NaN,NaN,RadioButton,NaN,0,Reason for visit missed,...,False,NaN,NaN,NaN,NaN,NaN,NaN,Data Management,False,8675974,8582374,7811536.0,7719869.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1147,EC_ADM,ECYN2,1,NaN,ECYN2,True,ECYN2,$3,Yes/No,NaN,NaN,RadioButton,NaN,0,Was dose administered for this visit?,...,False,NaN,NaN,NaN,NaN,NaN,NaN,Data Management,False,8826058,0,7942838.0,0.0,NaN,NaN
1150,EC_ADM,ECLWFAT2,4,NaN,ECLWFAT2,True,ECLWFAT2,$3,Yes/No,NaN,NaN,RadioButton,NaN,0,"Did the subject have a ""low-fat"" meal prior to...",...,False,NaN,NaN,NaN,NaN,NaN,NaN,Data Management,False,8826061,0,7942841.0,0.0,NaN,NaN

In [891]:
df1['DataDictionaryName_ref'] = df1['DataDictionaryName']
df1

,FormOID,FieldOID,Ordinal,DraftFieldNumber,DraftFieldName,DraftFieldActive,VariableOID,DataFormat,DataDictionaryName,UnitDictionaryName,CodingDictionary,ControlType,AcceptableFileExtensions,IndentLevel,PreText,...,LowerRange,UpperRange,NCLowerRange,NCUpperRange,ViewRestrictions,EntryRestrictions,ReviewGroups,IsVisualVerify,FDownloadedFromObjectId,FSourceObjectId,VDownloadedFromObjectId,VSourceObjectId,FSourceUrlId,VSourceUrlId,DataDictionaryName_ref
3,SV,SVSTAT,1,NaN,SVSTAT,True,SVSTAT,$10,SVSTAT,NaN,NaN,DropDownList,NaN,0,Visit status,...,NaN,NaN,NaN,NaN,NaN,NaN,Data Management,False,8675971,8582375,7811533.0,7719866.0,NaN,NaN,SVSTAT
6,SV,SVMRES,10,NaN,SVMRES,True,SVMRES,$10,COVIDND,NaN,NaN,RadioButton,NaN,0,Reason for visit missed,...,NaN,NaN,NaN,NaN,NaN,NaN,Data Management,False,8675974,8582374,7811536.0,7719869.0,NaN,NaN,COVIDND
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1147,EC_ADM,ECYN2,1,NaN,ECYN2,True,ECYN2,$3,Yes/No,NaN,NaN,RadioButton,NaN,0,Was dose administered for this visit?,...,NaN,NaN,NaN,NaN,NaN,NaN,Data Management,False,8826058,0,7942838.0,0.0,NaN,NaN,Yes/No
1150,EC_ADM,ECLWFAT2,4,NaN,ECLWFAT2,True,ECLWFAT2,$3,Yes/No,NaN,NaN,RadioButton,NaN,0,"Did the subject have a ""low-fat"" meal prior to...",...,NaN,NaN,NaN,NaN,NaN,NaN,Data Management,False,8826061,0,7942841.0,0.0,NaN,NaN,Yes/No

In [892]:
df1 = pd.DataFrame(df1,columns=['DataDictionaryName','DataDictionaryName_ref'])
df1

     DataDictionaryName DataDictionaryName_ref
3                SVSTAT                 SVSTAT
6               COVIDND                COVIDND
...                 ...                    ...
1147             Yes/No                 Yes/No
1150             Yes/No                 Yes/No

[537 rows x 2 columns]

In [893]:
df1 = df1.drop_duplicates(subset=['DataDictionaryName'])
df1

     DataDictionaryName DataDictionaryName_ref
3                SVSTAT                 SVSTAT
6               COVIDND                COVIDND
...                 ...                    ...
1005         DSTERM_EOS             DSTERM_EOS
1009     PRCDTH_DDORRES         PRCDTH_DDORRES

[119 rows x 2 columns]

In [894]:
df2 = pd.read_excel(r'G:\python\EC_QC\als.xlsx', sheet_name = 'DataDictionaryEntries')
df2

,DataDictionaryName,CodedData,Ordinal,UserDataString,Specify
0,SVSTAT,Done,1,Done,False
1,SVSTAT,Not done,2,Not done,False
...,...,...,...,...,...
647,IETEST,EXC 29,41,Known hypersensitivity to any component or exc...,False
648,IETEST,EXC 30,42,Concurrent participation in another therapeuti...,False

In [895]:
merge1 = pd.merge(df2,df1,how='left',on=['DataDictionaryName'])
merge1

,DataDictionaryName,CodedData,Ordinal,UserDataString,Specify,DataDictionaryName_ref
0,SVSTAT,Done,1,Done,False,SVSTAT
1,SVSTAT,Not done,2,Not done,False,SVSTAT
...,...,...,...,...,...,...
647,IETEST,EXC 29,41,Known hypersensitivity to any component or exc...,False,NaN
648,IETEST,EXC 30,42,Concurrent participation in another therapeuti...,False,NaN

In [896]:
merge1 = merge1[~merge1['DataDictionaryName_ref'].isna()]
merge1

,DataDictionaryName,CodedData,Ordinal,UserDataString,Specify,DataDictionaryName_ref
0,SVSTAT,Done,1,Done,False,SVSTAT
1,SVSTAT,Not done,2,Not done,False,SVSTAT
...,...,...,...,...,...,...
561,MLDSTXT,=>75% - <100%,5,=>75% - <100%,False,MLDSTXT
562,MLDSTXT,100%,6,100%,False,MLDSTXT

In [897]:
merge1 = pd.DataFrame(merge1,columns=['DataDictionaryName','CodedData','UserDataString'])
merge1

    DataDictionaryName      CodedData UserDataString
0               SVSTAT           Done           Done
1               SVSTAT       Not done       Not done
..                 ...            ...            ...
561            MLDSTXT  =>75% - <100%  =>75% - <100%
562            MLDSTXT           100%           100%

[563 rows x 3 columns]

In [898]:
# merge1 = DataDictEntries(Dict_BeingUsed) + varOID
# merge = CheckSteps

In [899]:
merge

,CheckName,DataFormat_x,VariableOID_x,FolderOID_x,FormOID_x,FieldOID_x,RecordPosition_x,StaticValue_y,DataFormat_y
0,DYN_SV_SET_SVDELYN_VISIBLE,CodedValue,SVSTAT,NaN,SV,SVSTAT,0.0,Done,$5
1,DYN_SV_SET_SVDRES_VISIBLE,CodedValue,SVSTAT,NaN,SV,SVSTAT,0.0,Done,$10
...,...,...,...,...,...,...,...,...,...
3689,Chk_SCR_DS_IC_ICOBM_MHTERM8,CodedValue,MHTERM8,SCR,MH_DHH,MHTERM8,0.0,WM,$2
3690,Chk_SCR_DS_IC_ICOBM_MHTERM8,CodedValue,MHTERM8,SCR,MH_DHH,MHTERM8,0.0,NaN,NaN

In [900]:
merge = merge.rename(columns={"VariableOID_x": "VariableOID"})
merge

,CheckName,DataFormat_x,VariableOID,FolderOID_x,FormOID_x,FieldOID_x,RecordPosition_x,StaticValue_y,DataFormat_y
0,DYN_SV_SET_SVDELYN_VISIBLE,CodedValue,SVSTAT,NaN,SV,SVSTAT,0.0,Done,$5
1,DYN_SV_SET_SVDRES_VISIBLE,CodedValue,SVSTAT,NaN,SV,SVSTAT,0.0,Done,$10
...,...,...,...,...,...,...,...,...,...
3689,Chk_SCR_DS_IC_ICOBM_MHTERM8,CodedValue,MHTERM8,SCR,MH_DHH,MHTERM8,0.0,WM,$2
3690,Chk_SCR_DS_IC_ICOBM_MHTERM8,CodedValue,MHTERM8,SCR,MH_DHH,MHTERM8,0.0,NaN,NaN

In [901]:
fields = pd.read_excel(r'G:\python\EC_QC\als.xlsx', sheet_name = 'Fields')

In [902]:
fields = fields[~fields['DataDictionaryName'].isna()]
fields

,FormOID,FieldOID,Ordinal,DraftFieldNumber,DraftFieldName,DraftFieldActive,VariableOID,DataFormat,DataDictionaryName,UnitDictionaryName,CodingDictionary,ControlType,AcceptableFileExtensions,IndentLevel,PreText,...,DoesNotBreakSignature,LowerRange,UpperRange,NCLowerRange,NCUpperRange,ViewRestrictions,EntryRestrictions,ReviewGroups,IsVisualVerify,FDownloadedFromObjectId,FSourceObjectId,VDownloadedFromObjectId,VSourceObjectId,FSourceUrlId,VSourceUrlId
3,SV,SVSTAT,1,NaN,SVSTAT,True,SVSTAT,$10,SVSTAT,NaN,NaN,DropDownList,NaN,0,Visit status,...,False,NaN,NaN,NaN,NaN,NaN,NaN,Data Management,False,8675971,8582375,7811533.0,7719866.0,NaN,NaN
6,SV,SVMRES,10,NaN,SVMRES,True,SVMRES,$10,COVIDND,NaN,NaN,RadioButton,NaN,0,Reason for visit missed,...,False,NaN,NaN,NaN,NaN,NaN,NaN,Data Management,False,8675974,8582374,7811536.0,7719869.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1147,EC_ADM,ECYN2,1,NaN,ECYN2,True,ECYN2,$3,Yes/No,NaN,NaN,RadioButton,NaN,0,Was dose administered for this visit?,...,False,NaN,NaN,NaN,NaN,NaN,NaN,Data Management,False,8826058,0,7942838.0,0.0,NaN,NaN
1150,EC_ADM,ECLWFAT2,4,NaN,ECLWFAT2,True,ECLWFAT2,$3,Yes/No,NaN,NaN,RadioButton,NaN,0,"Did the subject have a ""low-fat"" meal prior to...",...,False,NaN,NaN,NaN,NaN,NaN,NaN,Data Management,False,8826061,0,7942841.0,0.0,NaN,NaN

In [903]:
varOID_DictName = pd.DataFrame(fields,columns=['VariableOID','DataDictionaryName'])
varOID_DictName

     VariableOID DataDictionaryName
3         SVSTAT             SVSTAT
6         SVMRES            COVIDND
...          ...                ...
1147       ECYN2             Yes/No
1150    ECLWFAT2             Yes/No

[537 rows x 2 columns]

In [904]:
varOID_DictName = varOID_DictName.drop_duplicates(subset=['VariableOID'])
varOID_DictName

     VariableOID DataDictionaryName
3         SVSTAT             SVSTAT
6         SVMRES            COVIDND
...          ...                ...
1147       ECYN2             Yes/No
1150    ECLWFAT2             Yes/No

[530 rows x 2 columns]

In [905]:
chkstp_DictName = pd.merge(merge,varOID_DictName,how='left',on=['VariableOID'])
chkstp_DictName

,CheckName,DataFormat_x,VariableOID,FolderOID_x,FormOID_x,FieldOID_x,RecordPosition_x,StaticValue_y,DataFormat_y,DataDictionaryName
0,DYN_SV_SET_SVDELYN_VISIBLE,CodedValue,SVSTAT,NaN,SV,SVSTAT,0.0,Done,$5,SVSTAT
1,DYN_SV_SET_SVDRES_VISIBLE,CodedValue,SVSTAT,NaN,SV,SVSTAT,0.0,Done,$10,SVSTAT
...,...,...,...,...,...,...,...,...,...,...
3689,Chk_SCR_DS_IC_ICOBM_MHTERM8,CodedValue,MHTERM8,SCR,MH_DHH,MHTERM8,0.0,WM,$2,MHTERM8
3690,Chk_SCR_DS_IC_ICOBM_MHTERM8,CodedValue,MHTERM8,SCR,MH_DHH,MHTERM8,0.0,NaN,NaN,MHTERM8

In [906]:
chkstp_DictName['CodedData'] = chkstp_DictName['StaticValue_y']
chkstp_DictName

,CheckName,DataFormat_x,VariableOID,FolderOID_x,FormOID_x,FieldOID_x,RecordPosition_x,StaticValue_y,DataFormat_y,DataDictionaryName,CodedData
0,DYN_SV_SET_SVDELYN_VISIBLE,CodedValue,SVSTAT,NaN,SV,SVSTAT,0.0,Done,$5,SVSTAT,Done
1,DYN_SV_SET_SVDRES_VISIBLE,CodedValue,SVSTAT,NaN,SV,SVSTAT,0.0,Done,$10,SVSTAT,Done
...,...,...,...,...,...,...,...,...,...,...,...
3689,Chk_SCR_DS_IC_ICOBM_MHTERM8,CodedValue,MHTERM8,SCR,MH_DHH,MHTERM8,0.0,WM,$2,MHTERM8,WM
3690,Chk_SCR_DS_IC_ICOBM_MHTERM8,CodedValue,MHTERM8,SCR,MH_DHH,MHTERM8,0.0,NaN,NaN,MHTERM8,NaN

In [907]:
chkstp_DictName.to_excel(r'G:\python\EC_QC\chkstp_DictName.xlsx',index=False)

In [908]:
chkstp_DictName = chkstp_DictName[(~chkstp_DictName['DataDictionaryName'].isna()) & (~chkstp_DictName['StaticValue_y'].isna())]
chkstp_DictName

,CheckName,DataFormat_x,VariableOID,FolderOID_x,FormOID_x,FieldOID_x,RecordPosition_x,StaticValue_y,DataFormat_y,DataDictionaryName,CodedData
0,DYN_SV_SET_SVDELYN_VISIBLE,CodedValue,SVSTAT,NaN,SV,SVSTAT,0.0,Done,$5,SVSTAT,Done
1,DYN_SV_SET_SVDRES_VISIBLE,CodedValue,SVSTAT,NaN,SV,SVSTAT,0.0,Done,$10,SVSTAT,Done
...,...,...,...,...,...,...,...,...,...,...,...
3688,Chk_SCR_DS_IC_ICOBM_MHTERM8,CodedValue,ICOBM,SCR,DS_IC,ICOBM,NaN,Yes,$3,Yes/No,Yes
3689,Chk_SCR_DS_IC_ICOBM_MHTERM8,CodedValue,MHTERM8,SCR,MH_DHH,MHTERM8,0.0,WM,$2,MHTERM8,WM

In [909]:
merge1

    DataDictionaryName      CodedData UserDataString
0               SVSTAT           Done           Done
1               SVSTAT       Not done       Not done
..                 ...            ...            ...
561            MLDSTXT  =>75% - <100%  =>75% - <100%
562            MLDSTXT           100%           100%

[563 rows x 3 columns]

In [910]:
merge1['CodedData_DataDictEntries'] = merge1['CodedData']
merge1

    DataDictionaryName      CodedData UserDataString CodedData_DataDictEntries
0               SVSTAT           Done           Done                      Done
1               SVSTAT       Not done       Not done                  Not done
..                 ...            ...            ...                       ...
561            MLDSTXT  =>75% - <100%  =>75% - <100%             =>75% - <100%
562            MLDSTXT           100%           100%                      100%

[563 rows x 4 columns]

In [911]:
merge1 = merge1.rename(columns={"UserDataString": "UserDataString_DataDictEntries"})
merge1

,DataDictionaryName,CodedData,UserDataString_DataDictEntries,CodedData_DataDictEntries
0,SVSTAT,Done,Done,Done
1,SVSTAT,Not done,Not done,Not done
...,...,...,...,...
561,MLDSTXT,=>75% - <100%,=>75% - <100%,=>75% - <100%
562,MLDSTXT,100%,100%,100%

In [912]:
merge1.to_excel(r'G:\python\EC_QC\merge1.xlsx',index=False)

In [913]:
merge2 = pd.merge(chkstp_DictName,merge1,how='left',on=['DataDictionaryName','CodedData'])
merge2

,CheckName,DataFormat_x,VariableOID,FolderOID_x,FormOID_x,FieldOID_x,RecordPosition_x,StaticValue_y,DataFormat_y,DataDictionaryName,CodedData,UserDataString_DataDictEntries,CodedData_DataDictEntries
0,DYN_SV_SET_SVDELYN_VISIBLE,CodedValue,SVSTAT,NaN,SV,SVSTAT,0.0,Done,$5,SVSTAT,Done,Done,Done
1,DYN_SV_SET_SVDRES_VISIBLE,CodedValue,SVSTAT,NaN,SV,SVSTAT,0.0,Done,$10,SVSTAT,Done,Done,Done
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1951,Chk_SCR_DS_IC_ICOBM_MHTERM8,CodedValue,ICOBM,SCR,DS_IC,ICOBM,NaN,Yes,$3,Yes/No,Yes,Yes,Yes
1952,Chk_SCR_DS_IC_ICOBM_MHTERM8,CodedValue,MHTERM8,SCR,MH_DHH,MHTERM8,0.0,WM,$2,MHTERM8,WM,WM,WM

In [914]:
merge2.to_excel(r'G:\python\EC_QC\merge2.xlsx',index=False)

In [915]:
merge2['is_Equal'] = merge2['StaticValue_y'] == merge2['CodedData_DataDictEntries']
merge2

,CheckName,DataFormat_x,VariableOID,FolderOID_x,FormOID_x,FieldOID_x,RecordPosition_x,StaticValue_y,DataFormat_y,DataDictionaryName,CodedData,UserDataString_DataDictEntries,CodedData_DataDictEntries,is_Equal
0,DYN_SV_SET_SVDELYN_VISIBLE,CodedValue,SVSTAT,NaN,SV,SVSTAT,0.0,Done,$5,SVSTAT,Done,Done,Done,True
1,DYN_SV_SET_SVDRES_VISIBLE,CodedValue,SVSTAT,NaN,SV,SVSTAT,0.0,Done,$10,SVSTAT,Done,Done,Done,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1951,Chk_SCR_DS_IC_ICOBM_MHTERM8,CodedValue,ICOBM,SCR,DS_IC,ICOBM,NaN,Yes,$3,Yes/No,Yes,Yes,Yes,True
1952,Chk_SCR_DS_IC_ICOBM_MHTERM8,CodedValue,MHTERM8,SCR,MH_DHH,MHTERM8,0.0,WM,$2,MHTERM8,WM,WM,WM,True

In [916]:
merge2.to_excel(r'G:\python\EC_QC\result.xlsx',index=False)